@echo off
REM Tutorial 10: Launch a packaged client through the EAC bootstrapper.
REM
REM start_protected_game.exe reads EasyAntiCheat/Settings.json (generated by
REM RunUAT.bat ProtectEOSPackage) to find the game binary, then passes every
REM CLI arg through to it. This is the launch path EAC expects; anti-cheat
REM client init succeeds and the server's BeginSession/RegisterClient flow
REM runs normally.
REM
REM Prereqs: Package (BuildCookRun) + Protect (ProtectEOSPackage) have been
REM run - see Plugins/EOSAntiCheat/README.md. Protect places
REM start_protected_game.exe + EasyAntiCheat/ at the package root (NOT inside
REM <Project>/Binaries/Win64).
REM
REM Copy this file to <name>.Protected.local.bat, edit the path + credentials
REM for your machine, and run.

REM cd into the package root so UE's ../../../Engine/... relative DLL loads
REM resolve correctly when the game inherits cwd from the bootstrapper process.
cd /d "<Path to packaged output root (contains start_protected_game.exe)>"

start_protected_game.exe ^
    ThirdPersonMap ^
    -debug -game ^
    -AUTH_TYPE="developer" ^
    -AUTH_LOGIN="localhost:8081" ^
    -AUTH_PASSWORD="<DevAuthTool Credential name>" ^
    -epicapp="Client"
